language: cpp
before_install:
    - lsb_release -a
    - which $CXX
    - $CXX --version
    - getconf _NPROCESSORS_ONLN
install: 
    - sudo mkdir -p /etc/apt/sources.list.d/
#    - sudo touch /etc/apt/sources.list.d/llvm.list
#    - sudo chmod a+rw /etc/apt/sources.list.d/llvm.list
#    - echo "deb http://llvm.org/apt/precise/ llvm-toolchain-precise main" > /etc/apt/sources.list.d/llvm.list
#    - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
    - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo add-apt-repository -y ppa:boost-latest/ppa
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install libboost1.54-all-dev libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-net1.2-dev libsdl-sound1.2-dev libsdl1.2-dev libavcodec-dev libavformat-dev libavdevice-dev libavutil-dev libswscale-dev libpostproc-dev libsdl-ttf2.0-dev pastebinit
    - wget http://launchpadlibrarian.net/155807880/iwyu_3.3-3_amd64.deb
    - sudo dpkg --force-all -i iwyu_3.3-3_amd64.deb
    - dpkg -L iwyu
    - dpkg -L iwyu | pastebinit
    - wget https://gist.github.com/janisozaur/7727632/raw/5d33cf38956cf6dba4feebf6d01aad98e689e90c/iwyu-wrapper
    - chmod a+x iwyu-wrapper
    - export CXX=$(pwd)/iwyu-wrapper
#    - if [ "$CXX" = "clang++" ]; then sudo apt-get install clang-3.4; fi
#    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq qtbase5-dev qtdeclarative5-dev qt5-default qt5-qmake qtbase5-dev-tools qtmultimedia5-dev g++-4.8; fi
before_script:
    - dpkg -l | pastebinit
    - export ENABLE_QT_PARTS=$(if [ "$CXX" = "g++" ]; then echo ON; else echo OFF ; fi)
    - echo $ENABLE_QT_PARTS
#    - if [ "$CXX" = "clang++" ]; then export CXX="/usr/bin/clang++" CC="/usr/bin/clang"; fi
#    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
    - which $CXX
    - $CXX --version
script:
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_LAUNCHER=$ENABLE_QT_PARTS -DENABLE_TEST=ON -DENABLE_EDITOR=$ENABLE_QT_PARTS .
    - make -j 6
after_script:
    - pastebinit compile_commands.json
    - find . -name '*iwyu.txt' -print0 | xargs -0 tar cf iwyu.tar 
    - xz -9ev iwyu.tar
    - ls -l iwyu.tar.xz
    - ls -lh iwyu.tar.xz
    - base64 iwyu.tar.xz | pastebinit
compiler:
    - clang
